import type { BidviaRouteCapability } from './contracts.js';

export const bidviaRouteCapabilities: ReadonlyArray<BidviaRouteCapability> = [
  {
    helperKey: 'createProvisionalAgent',
    routePathTemplate: '/runtime/agents/provisional',
    httpMethod: 'POST',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'queryProvisionalAgent',
    routePathTemplate: '/runtime/agents/provisional',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'claimProvisionalAgent',
    routePathTemplate: '/runtime/agents/provisional/claim',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'postHeartbeat',
    routePathTemplate: '/runtime/agents/:registrationId/heartbeat',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'uploadSync',
    routePathTemplate: '/runtime/agents/:registrationId/sync/upload',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'downloadSync',
    routePathTemplate: '/runtime/agents/:registrationId/sync/download',
    httpMethod: 'GET',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'submitEvidence',
    routePathTemplate: '/runtime/agents/:registrationId/evidence-submissions',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'submitProposal',
    routePathTemplate: '/runtime/agents/:registrationId/proposals',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'listAccountAgents',
    routePathTemplate: '/runtime/account/agents',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgent',
    routePathTemplate: '/runtime/account/agents/:agent_registration_id',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAccountAgentBindings',
    routePathTemplate: '/runtime/account/agent-bindings',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAccountRecords',
    routePathTemplate: '/runtime/account/records',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentPresence',
    routePathTemplate: '/runtime/agents/:agent_registration_id/presence',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentAuthority',
    routePathTemplate: '/runtime/agents/:agent_registration_id/authority',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listCanonicalSemanticConcepts',
    routePathTemplate: '/runtime/canonical-semantic-concepts',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getCanonicalSemanticConcept',
    routePathTemplate: '/runtime/canonical-semantic-concepts/:canonical_semantic_concept_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingBases',
    routePathTemplate: '/runtime/pricing-bases',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingBasis',
    routePathTemplate: '/runtime/pricing-bases/:pricing_basis_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listDocumentArtifacts',
    routePathTemplate: '/runtime/document-artifacts',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getDocumentArtifact',
    routePathTemplate: '/runtime/document-artifacts/:document_artifact_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listMediaAssets',
    routePathTemplate: '/runtime/media-assets',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getMediaAsset',
    routePathTemplate: '/runtime/media-assets/:media_asset_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listEvidenceAssets',
    routePathTemplate: '/runtime/evidence-assets',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getEvidenceAsset',
    routePathTemplate: '/runtime/evidence-assets/:evidence_asset_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAttachmentBindings',
    routePathTemplate: '/runtime/attachment-bindings',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAttachmentBinding',
    routePathTemplate: '/runtime/attachment-bindings/:attachment_binding_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createCommercialAction',
    routePathTemplate: '/runtime/commercial-actions',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'getCommercialActionStatus',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/status',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'policyCheckCommercialAction',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/policy-check',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'requestCommercialActionApproval',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/request-approval',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'executeCommercialAction',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/execute',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'getCommercialActionReceipt',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/receipt',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getCommercialActionAudit',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/audit',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createListing',
    routePathTemplate: '/runtime/listings',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'activateListing',
    routePathTemplate: '/runtime/listings/:listingId/activate',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'generateMatchCandidates',
    routePathTemplate: '/runtime/listings/:listingId/match-candidates',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createConnectionRequest',
    routePathTemplate: '/runtime/connection-requests',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'approveConnectionRequest',
    routePathTemplate: '/runtime/approvals/:approvalRequestId/decision',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'exportOpportunityPackage',
    routePathTemplate: '/runtime/opportunities/:opportunityId/package-export',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'buildIndustryUniverseScenarioPlan',
    routePathTemplate: '/scenarios/industry-universe',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
    scenarioRouteSteps: [
      {
        routeKey: 'createListing',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'activateListing',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'generateMatchCandidates',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
  {
    helperKey: 'buildConnectionApprovalScenarioPlan',
    routePathTemplate: '/scenarios/connection-approval',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
    scenarioRouteSteps: [
      {
        routeKey: 'createConnectionRequest',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'approveConnectionRequest',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
  {
    helperKey: 'buildOpportunityPackageHandoffPlan',
    routePathTemplate: '/scenarios/opportunity-package-handoff',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
    scenarioRouteSteps: [
      {
        routeKey: 'exportOpportunityPackage',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
];

export function getRouteCapability(helperKey: string): BidviaRouteCapability | undefined {
  return bidviaRouteCapabilities.find((capability) => capability.helperKey === helperKey);
}
