import type {
  BidviaNextStageReadRouteDiscoveryGroup,
  BidviaRouteCapabilityContextSemantic,
  BidviaRouteCapability,
} from './contracts.js';
import {
  buildCapabilityPlaneView,
  getCapabilityPlaneCapabilityMode,
  getCapabilityPlaneReadTruthSurface,
} from './capability-plane.js';
import { getEventNotificationPlaneCapabilityMode } from './event-notification-plane.js';
import { getTaskPlaneCapabilityMode } from './task-plane.js';

type BidviaRouteCapabilityWithOptionalContextSemantic = Omit<BidviaRouteCapability, 'contextSemantic'> & {
  contextSemantic?: BidviaRouteCapabilityContextSemantic;
};

function applyRouteContextSemantic(
  capability: BidviaRouteCapabilityWithOptionalContextSemantic,
): BidviaRouteCapability {
  const taskPlaneCapabilityMode = getTaskPlaneCapabilityMode(capability.helperKey);
  const eventNotificationPlaneCapabilityMode = getEventNotificationPlaneCapabilityMode(capability.helperKey);

  return {
    ...capability,
    contextSemantic: capability.contextSemantic ?? capability.accessContextFamily,
    ...(getCapabilityPlaneCapabilityMode(capability.helperKey) === undefined
      ? {}
      : { capabilityPlaneCapabilityMode: getCapabilityPlaneCapabilityMode(capability.helperKey) }),
    ...(getCapabilityPlaneReadTruthSurface(capability.helperKey) === undefined
      ? {}
      : {
          dispatchEligibilityDerivedFromCapabilityReadTruth: false,
          governedRunAuthorizationDerivedFromCapabilityReadTruth: false,
        }),
    ...(taskPlaneCapabilityMode === undefined ? {} : { taskPlaneCapabilityMode }),
    ...(eventNotificationPlaneCapabilityMode === undefined
      ? {}
      : { eventNotificationPlaneCapabilityMode }),
  };
}

const bidviaShippedExpandedReadRouteCapabilities: ReadonlyArray<BidviaRouteCapabilityWithOptionalContextSemantic> = [
  {
    helperKey: 'getAgentReadiness',
    routePathTemplate: '/runtime/agents/:agent_registration_id/readiness',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentSummary',
    routePathTemplate: '/runtime/agents/:agent_registration_id/summary',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAgentRegistrations',
    routePathTemplate: '/runtime/agents/registrations',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentRegistration',
    routePathTemplate: '/runtime/agents/:agent_registration_id',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAuthorityProfiles',
    routePathTemplate: '/runtime/authority-profiles',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentAuthorityProfile',
    routePathTemplate: '/runtime/agents/:agent_registration_id/authority-profile',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentAuthorityLadder',
    routePathTemplate: '/runtime/agents/:agent_registration_id/authority-ladder',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listCapabilityProfiles',
    routePathTemplate: '/runtime/capability-profiles',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentCapabilityProfile',
    routePathTemplate: '/runtime/agents/:agent_registration_id/capability-profile',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'postAgentAuthorityProfile',
    routePathTemplate: '/runtime/agents/:agent_registration_id/authority-profile',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'postAgentAuthorityLadder',
    routePathTemplate: '/runtime/agents/:agent_registration_id/authority-ladder',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'postAgentCapabilityProfile',
    routePathTemplate: '/runtime/agents/:agent_registration_id/capability-profile',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'listCanonicalSemanticLabels',
    routePathTemplate: '/runtime/canonical-semantic-labels',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getCanonicalSemanticLabel',
    routePathTemplate: '/runtime/canonical-semantic-labels/:canonical_semantic_label_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listCanonicalSemanticMappings',
    routePathTemplate: '/runtime/canonical-semantic-mappings',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getCanonicalSemanticMapping',
    routePathTemplate: '/runtime/canonical-semantic-mappings/:canonical_semantic_mapping_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingRuleAtoms',
    routePathTemplate: '/runtime/pricing-rule-atoms',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingRuleAtom',
    routePathTemplate: '/runtime/pricing-rule-atoms/:pricing_rule_atom_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingQuotationMethodModules',
    routePathTemplate: '/runtime/pricing-quotation-method-modules',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingQuotationMethodModule',
    routePathTemplate: '/runtime/pricing-quotation-method-modules/:pricing_quotation_method_module_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingQuoteTemplates',
    routePathTemplate: '/runtime/pricing-quote-templates',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingQuoteTemplate',
    routePathTemplate: '/runtime/pricing-quote-templates/:pricing_quote_template_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingQuotations',
    routePathTemplate: '/runtime/pricing-quotations',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingQuotation',
    routePathTemplate: '/runtime/pricing-quotations/:pricing_quotation_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingExplanations',
    routePathTemplate: '/runtime/pricing-explanations',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingExplanation',
    routePathTemplate: '/runtime/pricing-explanations/:pricing_explanation_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
];

const bidviaBaseRouteCapabilities: ReadonlyArray<BidviaRouteCapabilityWithOptionalContextSemantic> = [
  {
    helperKey: 'listPublicIntegrationApps',
    routePathTemplate: '/runtime/public/integration-apps',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createAccountIntegrationApp',
    routePathTemplate: '/runtime/account/integration-apps',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'listAccountIntegrationApps',
    routePathTemplate: '/runtime/account/integration-apps',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createAccountIntegrationInstallation',
    routePathTemplate: '/runtime/account/integration-installations',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'listAccountIntegrationInstallations',
    routePathTemplate: '/runtime/account/integration-installations',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'connectAccountIntegrationInstallation',
    routePathTemplate: '/runtime/account/integration-installations/:integrationInstallationId/connection',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'submitIntegrationOnboardingContract',
    routePathTemplate: '/runtime/integrations/:integrationCode/onboarding-contract',
    httpMethod: 'POST',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'logInHaisiWms',
    routePathTemplate: '/runtime/integrations/haisi-wms/login',
    httpMethod: 'POST',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'listHaisiWmsWarehouses',
    routePathTemplate: '/runtime/integrations/haisi-wms/warehouses',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createHaisiWmsInbound',
    routePathTemplate: '/runtime/integrations/haisi-wms/inbound',
    httpMethod: 'POST',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'listAccountIntegrationCapabilities',
    routePathTemplate: '/runtime/account/integration-capabilities',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgentIntegrationEligibility',
    routePathTemplate: '/runtime/account/agents/:agentId/integrations/:integrationCode/eligibility',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createProvisionalAgent',
    routePathTemplate: '/runtime/agents/provisional',
    httpMethod: 'POST',
    accessContextFamily: 'tenant',
    contextSemantic: 'public-provisional',
    requiredContext: ['tenantId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'queryProvisionalAgent',
    routePathTemplate: '/runtime/agents/provisional',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    contextSemantic: 'public-provisional',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'claimProvisionalAgent',
    routePathTemplate: '/runtime/agents/provisional/claim',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'postHeartbeat',
    routePathTemplate: '/runtime/agents/:registrationId/heartbeat',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'uploadSync',
    routePathTemplate: '/runtime/agents/:registrationId/sync/upload',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'downloadSync',
    routePathTemplate: '/runtime/agents/:registrationId/sync/download',
    httpMethod: 'GET',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'submitEvidence',
    routePathTemplate: '/runtime/agents/:registrationId/evidence-submissions',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'submitProposal',
    routePathTemplate: '/runtime/agents/:registrationId/proposals',
    httpMethod: 'POST',
    accessContextFamily: 'registration',
    requiredContext: ['tenantId', 'registrationId', 'principalId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'getAccountMe',
    routePathTemplate: '/runtime/account/me',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'selectOrg',
    routePathTemplate: '/runtime/account/select-org',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'createAccountMembershipInvitation',
    routePathTemplate: '/runtime/account/memberships/invitations',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'acceptAccountMembershipInvitation',
    routePathTemplate: '/runtime/account/memberships/accept-invitation',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'transferAccountMembershipAdmin',
    routePathTemplate: '/runtime/account/memberships/:membership_binding_id/transfer-admin',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'removeAccountMembership',
    routePathTemplate: '/runtime/account/memberships/:membership_binding_id/remove',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'patchAgentSelfService',
    routePathTemplate: '/runtime/account/agents/:agentId/self-service',
    httpMethod: 'PATCH',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'listAccountAgents',
    routePathTemplate: '/runtime/account/agents',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgent',
    routePathTemplate: '/runtime/account/agents/:agentId',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgentDispatchAuthority',
    routePathTemplate: '/runtime/account/agents/:agentId/dispatch-authority',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createAccountAgentDispatchAuthorityRequest',
    routePathTemplate: '/runtime/account/agents/:agentId/dispatch-authority-requests',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'getAccountAgentClosureStatus',
    routePathTemplate: '/runtime/account/agents/:agentId/closure-status',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'postAccountAgentExecutionPresence',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/presence',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'getAccountAgentExecutionStatus',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/status',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'uploadAccountAgentExecutionSync',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/sync/upload',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'downloadAccountAgentExecutionSync',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/sync/download',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'submitAccountAgentExecutionEvidence',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/evidence-submissions',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'submitAccountAgentExecutionProposal',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/proposals',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L2-registration-runtime',
    localCapabilityRiskTier: 'runtime-execution',
  },
  {
    helperKey: 'createAccountAgentExecutionListing',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/listings',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'activateAccountAgentExecutionListing',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/listings/:listing_id/activate',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'updateAccountAgentExecutionListing',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/listings/:listing_id',
    httpMethod: 'PATCH',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'getAccountAgentExecutionListingStatus',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/listings/:listing_id/status',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgentExecutionOpportunityStatus',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/opportunities/:opportunityId/status',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgentExecutionOpportunityEndState',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/opportunities/:opportunityId/end-state',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgentExecutionListingMaterializationStatus',
    routePathTemplate: '/runtime/account/agents/:agentId/execution/listings/:listing_id/materialization-status',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'refreshAccountAgentAuthorization',
    routePathTemplate: '/runtime/account/agents/:agentId/governed-runtime/authorization-refresh',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'createAccountAgentExternalBinding',
    routePathTemplate: '/runtime/account/agents/:agentId/external-account-bindings',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'listAccountAgentBindings',
    routePathTemplate: '/runtime/account/agent-bindings',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAccountRecords',
    routePathTemplate: '/runtime/account/records',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'decideDispatchAuthorityRequest',
    routePathTemplate: '/operator/dispatch-authority-requests/:request_id/decision',
    httpMethod: 'POST',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'getAgentPresence',
    routePathTemplate: '/runtime/agents/:agent_registration_id/presence',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAgentAuthority',
    routePathTemplate: '/runtime/agents/:agent_registration_id/authority',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listCanonicalSemanticConcepts',
    routePathTemplate: '/runtime/canonical-semantic-concepts',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getCanonicalSemanticConcept',
    routePathTemplate: '/runtime/canonical-semantic-concepts/:canonical_semantic_concept_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listPricingBases',
    routePathTemplate: '/runtime/pricing-bases',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getPricingBasis',
    routePathTemplate: '/runtime/pricing-bases/:pricing_basis_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listDocumentArtifacts',
    routePathTemplate: '/runtime/document-artifacts',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getDocumentArtifact',
    routePathTemplate: '/runtime/document-artifacts/:document_artifact_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listMediaAssets',
    routePathTemplate: '/runtime/media-assets',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getMediaAsset',
    routePathTemplate: '/runtime/media-assets/:media_asset_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listEvidenceAssets',
    routePathTemplate: '/runtime/evidence-assets',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getEvidenceAsset',
    routePathTemplate: '/runtime/evidence-assets/:evidence_asset_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'listAttachmentBindings',
    routePathTemplate: '/runtime/attachment-bindings',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAttachmentBinding',
    routePathTemplate: '/runtime/attachment-bindings/:attachment_binding_id',
    httpMethod: 'GET',
    accessContextFamily: 'tenant',
    requiredContext: ['tenantId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  ...bidviaShippedExpandedReadRouteCapabilities,
  {
    helperKey: 'listParticipationStates',
    routePathTemplate: '/runtime/agents/:agent_registration_id/participation-states',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getParticipationState',
    routePathTemplate: '/runtime/agents/:agent_registration_id/participation-states/:participation_state_id',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createParticipationState',
    routePathTemplate: '/runtime/agents/:agent_registration_id/participation-states',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createLease',
    routePathTemplate: '/runtime/account/agents/:agentId/leases',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'listTaskDispatches',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getAccountAgentGovernedWorkClosure',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/governed-work-closure',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getNotification',
    routePathTemplate: '/runtime/account/agents/:agentId/notifications/:notification_id',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'acknowledgeNotification',
    routePathTemplate: '/runtime/account/agents/:agentId/notifications/:notification_id/acknowledgements',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'assignTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/assign',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'suspendTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/suspend',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'resumeTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/resume',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'completeTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/complete',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createTaskDispatchOutcome',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/outcomes',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createTaskDispatchEvidenceBundle',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/evidence-bundles',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createTaskDispatchConfirmationCycle',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/confirmation-cycles',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'failTaskDispatch',
    routePathTemplate: '/runtime/account/agents/:agentId/task-dispatches/:task_dispatch_id/fail',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createClaim',
    routePathTemplate: '/runtime/account/agents/:agentId/claims',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'acceptClaim',
    routePathTemplate: '/runtime/account/agents/:agentId/claims/:claim_id/accept',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'rejectClaim',
    routePathTemplate: '/runtime/account/agents/:agentId/claims/:claim_id/reject',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createCommercialAction',
    routePathTemplate: '/runtime/commercial-actions',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'getCommercialActionStatus',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/status',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'policyCheckCommercialAction',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/policy-check',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'requestCommercialActionApproval',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/request-approval',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'executeCommercialAction',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/execute',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'getCommercialActionReceipt',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/receipt',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'getCommercialActionAudit',
    routePathTemplate: '/runtime/commercial-actions/:commercialActionRequestId/audit',
    httpMethod: 'GET',
    accessContextFamily: 'principal-governed-read',
    requiredContext: ['tenantId', 'principalId'],
    scope: 'read',
    level: 'atomic-route',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'createListing',
    routePathTemplate: '/runtime/listings',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'activateListing',
    routePathTemplate: '/runtime/listings/:listingId/activate',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'generateMatchCandidates',
    routePathTemplate: '/runtime/listings/:listingId/match-candidates',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'createConnectionRequest',
    routePathTemplate: '/runtime/connection-requests',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'approveConnectionRequest',
    routePathTemplate: '/runtime/approvals/:approvalRequestId/decision',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'exportOpportunityPackage',
    routePathTemplate: '/runtime/opportunities/:opportunityId/package-export',
    httpMethod: 'POST',
    accessContextFamily: 'operator-company',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'atomic-route',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'inspectClaimantPrecondition',
    routePathTemplate: '/product/claimant/precondition/inspect',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['sessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'establishClaimantCanonicalCompanyPublicPrecondition',
    routePathTemplate: '/product/claimant/precondition/establish-canonical-company-public',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['sessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'inspectClaimantReadiness',
    routePathTemplate: '/product/claimant/readiness/inspect',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'repairClaimantReadiness',
    routePathTemplate: '/product/claimant/readiness/repair',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'runClaimantTaskEntry',
    routePathTemplate: '/product/claimant/task-entry/run',
    httpMethod: 'POST',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'inspectClaimantHandoff',
    routePathTemplate: '/product/claimant/handoff/inspect',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'inspectClaimantOpportunityStatus',
    routePathTemplate: '/product/claimant/handoff/opportunity-status',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'inspectClaimantOpportunityEndState',
    routePathTemplate: '/product/claimant/handoff/opportunity-end-state',
    httpMethod: 'GET',
    accessContextFamily: 'session',
    contextSemantic: 'session',
    requiredContext: ['tenantId', 'sessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'consumeOperatorHandoff',
    routePathTemplate: '/product/operator/handoff/consume',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'runOperatorMatching',
    routePathTemplate: '/product/operator/progression/match',
    httpMethod: 'POST',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'runOperatorConnectionContinuation',
    routePathTemplate: '/product/operator/progression/connect',
    httpMethod: 'POST',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'runOperatorApprovalContinuation',
    routePathTemplate: '/product/operator/progression/approve',
    httpMethod: 'POST',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'runOperatorPackageExport',
    routePathTemplate: '/product/operator/progression/package-export',
    httpMethod: 'POST',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'runOperatorCommercialAction',
    routePathTemplate: '/product/operator/closure/commercial-action',
    httpMethod: 'POST',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
  },
  {
    helperKey: 'inspectOperatorCommercialAction',
    routePathTemplate: '/product/operator/closure/inspect',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'inspectPlatformManagedEntry',
    routePathTemplate: '/product/platform-managed/entry/inspect',
    httpMethod: 'GET',
    accessContextFamily: 'scenario',
    requiredContext: [],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'inspectPlatformManagedReadiness',
    routePathTemplate: '/product/platform-managed/readiness/inspect',
    httpMethod: 'GET',
    accessContextFamily: 'scenario',
    requiredContext: [],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'runPlatformManagedProgression',
    routePathTemplate: '/product/platform-managed/progression/run',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: [],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
  },
  {
    helperKey: 'inspectOperatorHandoffFailure',
    routePathTemplate: '/product/operator/handoff/failure-inspect',
    httpMethod: 'GET',
    accessContextFamily: 'admin-session',
    contextSemantic: 'admin-session',
    requiredContext: ['tenantId', 'adminSessionId'],
    scope: 'read',
    level: 'scenario-helper',
    localCapabilityTier: 'L0-observe-only',
    localCapabilityRiskTier: 'observe-only',
  },
  {
    helperKey: 'buildIndustryUniverseScenarioPlan',
    routePathTemplate: '/scenarios/industry-universe',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
    scenarioRouteSteps: [
      {
        routeKey: 'createListing',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'activateListing',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'generateMatchCandidates',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
  {
    helperKey: 'executeIndustryUniverseScenario',
    routePathTemplate: '/scenarios/industry-universe',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L3-governed-commercial',
    localCapabilityRiskTier: 'governed-commercial',
    scenarioRouteSteps: [
      {
        routeKey: 'createListing',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'activateListing',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'generateMatchCandidates',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
  {
    helperKey: 'buildConnectionApprovalScenarioPlan',
    routePathTemplate: '/scenarios/connection-approval',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
    scenarioRouteSteps: [
      {
        routeKey: 'createConnectionRequest',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
      {
        routeKey: 'approveConnectionRequest',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
  {
    helperKey: 'buildOpportunityPackageHandoffPlan',
    routePathTemplate: '/scenarios/opportunity-package-handoff',
    httpMethod: 'POST',
    accessContextFamily: 'scenario',
    requiredContext: ['tenantId', 'principalId', 'companyId'],
    scope: 'write',
    level: 'scenario-helper',
    localCapabilityTier: 'L1-review-safe',
    localCapabilityRiskTier: 'review-safe',
    scenarioRouteSteps: [
      {
        routeKey: 'exportOpportunityPackage',
        requiredContext: ['tenantId', 'principalId', 'companyId'],
      },
    ],
  },
];

export const bidviaRouteCapabilities: ReadonlyArray<BidviaRouteCapability> = [
  ...bidviaBaseRouteCapabilities,
  ...bidviaShippedExpandedReadRouteCapabilities,
].map((capability) => applyRouteContextSemantic(capability));

export const bidviaNextStageReadRouteDiscoveryGroups: ReadonlyArray<
  BidviaNextStageReadRouteDiscoveryGroup
> = [
  {
    groupKey: 'governance-deep-reads',
    label: 'Richer governance deep reads',
    description:
      'Metadata-only bucket reserved for future governance deep-read additions beyond the helpers already shipped in routeCapabilities.',
    discoveryStatus: 'metadata-only',
    discoveryOnly: true,
    serverTruthClaimed: false,
    members: [],
  },
  {
    groupKey: 'semantic-truth-fetch-expansion',
    label: 'Broader semantic truth-fetch families',
    description:
      'Metadata-only bucket reserved for future semantic truth-fetch additions beyond the helpers already shipped in routeCapabilities.',
    discoveryStatus: 'metadata-only',
    discoveryOnly: true,
    serverTruthClaimed: false,
    members: [],
  },
  {
    groupKey: 'pricing-truth-fetch-expansion',
    label: 'Broader pricing truth-fetch families',
    description:
      'Metadata-only bucket reserved for future pricing truth-fetch additions beyond the helpers already shipped in routeCapabilities.',
    discoveryStatus: 'metadata-only',
    discoveryOnly: true,
    serverTruthClaimed: false,
    members: [],
  },
  {
    groupKey: 'asset-truth-fetch-expansion',
    label: 'Broader asset truth-fetch families',
    description:
      'Metadata-only bucket reserved for future asset truth-fetch additions beyond the helpers already shipped in routeCapabilities.',
    discoveryStatus: 'metadata-only',
    discoveryOnly: true,
    serverTruthClaimed: false,
    members: [],
  },
];

export function getRouteCapability(helperKey: string): BidviaRouteCapability | undefined {
  return bidviaRouteCapabilities.find((capability) => capability.helperKey === helperKey);
}

export function exportRouteCapabilityCatalog(): BidviaRouteCapability[] {
  const capabilityPlane = buildCapabilityPlaneView();

  if (!capabilityPlane.localSnapshots.descriptiveOnly) {
    throw new Error('Capability discovery must remain descriptive-only until packet-complete Core truth exists.');
  }

  return structuredClone([...bidviaRouteCapabilities]);
}

export function getNextStageReadRouteDiscoveryGroup(
  groupKey: BidviaNextStageReadRouteDiscoveryGroup['groupKey'],
): BidviaNextStageReadRouteDiscoveryGroup | undefined {
  return bidviaNextStageReadRouteDiscoveryGroups.find((group) => group.groupKey === groupKey);
}
